version: "3.8"

services:
    python-service-builder:
        build:
            context: .
            dockerfile: Dockerfile-python
        image: python-service

    javascript-service-builder:
        build:
            context: .
            dockerfile: Dockerfile-javascript
        image: javascript-service
